### ISSUE TITLE
3D柱状图位置错位啦

### ISSUE THREAD

**Issue by bh-lay** [Sobranier/github-chart#1]
![qq 20150630115852](https://cloud.githubusercontent.com/assets/4100462/8423669/98ce4826-1f1f-11e5-98c4-ded9097d5ec1.png)
我也不知道咋回事儿，图片变成了这个样纸

**Comment by Sobranier** [comment]
1.0.1.1版本有一个小bug，目前已经修复，需要你手动更新到1.0.1.2版
![2015-06-30 12 59 30](https://cloud.githubusercontent.com/assets/7440073/8424125/e67b340a-1f27-11e5-8e69-de7d415f0e72.png)

**Comment by bh-lay** [comment]
yeah 原来已经搞定了，那我close这个issue了！
