### ISSUE TITLE
连击显示不对

### ISSUE THREAD

**Issue by xwartz** [Sobranier/github-chart#10]
好像显示都是 0，是个 bug。

还有最长连击时间显示太丑了，字太长久和 days 显示到一起了。

**Comment by Sobranier** [comment]
你好，有没有具体哪个人的首页作为 bug 参考，现在看我的首页好像是对的

**Comment by xwartz** [comment]
我的就不对，现在当前连击显示是 0

**Comment by Sobranier** [comment]
好的，确认一个 bug，我会尽快修复

**Comment by Sobranier** [comment]
该 bug 已有同学解决
https://github.com/Sobranier/github-chart/pull/13
最新版本2.1.0
