### ISSUE TITLE
图像重叠

### ISSUE THREAD

**Issue by CxdInitial** [Sobranier/github-chart#15]
在Macbook air上图像重叠。
![2018-03-26 8 52 51](https://user-images.githubusercontent.com/25840869/37882137-29910cd2-30d3-11e8-9610-23985c66209d.png)

**Comment by Sobranier** [comment]
收到，之前没有对最大高度做优化

你有兴趣加入修改吗= =

**Comment by CxdInitial** [comment]
抱歉 对于前端不太了解，可能帮不了什么忙
