### ISSUE TITLE
柱状图展示空白

### ISSUE THREAD

**Issue by Yuzeyang** [Sobranier/github-chart#18]
![image](https://user-images.githubusercontent.com/12770548/107460699-9212c400-6b93-11eb-8c81-21d37e0fd24c.png)

![image](https://user-images.githubusercontent.com/12770548/107460656-76a7b900-6b93-11eb-9bd6-e86317d6cd13.png)

**Comment by geekyouth** [comment]
我也遇到了。

**Comment by Sobranier** [comment]
> 我也遇到了。

@baijunpeng666

**Comment by Sobranier** [comment]
> 我也遇到了。

已修复，请更新版本到2.1.1
