### ISSUE TITLE
README文件的小问题

### ISSUE THREAD

**Issue by vra** [Sobranier/github-chart#8]
Hi，我查看README的文件时候，发现有一些小问题：
1. 截图左侧显示了一些个人信息，但没有显示全，所以我想能不能修改成只显示插件的效果部分或者显示完整的个人信息和插件效果部分？
2. `For Developers` 那部分那句话貌似不完整，run后面没有写执行的命令

所以提了这个issue，希望能对这个很酷的项目做一点贡献 😄

**Comment by Sobranier** [comment]
你好，我先参考你的建议进行一些改进，如果感觉还有不妥的地方你可以再给我提 pr😄

**Comment by vra** [comment]
谢谢你对我建议的采纳，希望这个项目做的越来越好😄。我打算参考你的`For Developers`那部分的命令，自己先学习下这个插件的实现的原理，后面看能不能给项目贡献一些实质性的代码
